name: 编译 mtk6771 安卓P a9内核 (集成 KernelSU - 无手动 Hook)

on:
  workflow_dispatch:
    inputs:
      device:
        type: choice
        description: '设备型号'
        required: true
        options:
        - '17061'
        - '17197'
        - '17331'
        - '18011'
        - '18161'
        - '18311'
        - '18531'
        - '19091'
        - '19151'
        - '19350'
        - '19391'
        - '19531'
      
        
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: 构建编译内核环境
      run: |
        sudo apt-get update
        sudo -E apt-get -y -qq install git make bc bison ccache openssl dos2unix zip kmod cpio flex libelf-dev curl libssl-dev libtfm-dev wget device-tree-compiler ca-certificates python3 python2 libtinfo5 binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace
    - name: 下载 Gcc编译器
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        
        mkdir gcc64
        wget -O gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/961622e926a1b21382dba4dd9fe0e5fb3ee5ab7c.tar.gz
        tar -C gcc64/ -zxvf gcc-aarch64.tar.gz
    
        mkdir gcc32
        wget -O gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/cb7b3ac1b7fdb49474ff68761909934d1142f594.tar.gz
        tar -C gcc32/ -zxvf gcc-arm.tar.gz
    
    - name: 下载Clang编译器
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        mkdir clang-aosp
        git clone -q --depth=1 https://github.com/wu17481748/android_prebuilts_clang_host_linux-x86_clang-4691093 clang-aosp
    
    - name: 下载内核源码
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/Winkmoon/PCAM10_KERNEL/ android-kernel
        cd android-kernel
    - name: KernelSU
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        rm -rf KernelSU
        echo "KERNEL_VERSION=androidP" >> $GITHUB_ENV
        echo "KERNEL_NAME=mtk6771" >> $GITHUB_ENV

        export KSU_VERSION=$KSU_VERSION
        sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=$KSU_VERSION/" kernel/Makefile
        
        # 启用必要的内核配置
        CONFIG_FILE="arch/arm64/configs/oppo6771_${{ github.event.inputs.device }}_defconfig"
        echo "CONFIG_MODULE_SIG=n" >> $CONFIG_FILE
        echo "CONFIG_MODULE_SIG_ALL=n" >> $CONFIG_FILE
        echo "CONFIG_MODULES=y" >> $CONFIG_FILE
        echo "CONFIG_KALLSYMS=y" >> $CONFIG_FILE
        echo "CONFIG_KALLSYMS_ALL=y" >> $CONFIG_FILE
        echo "CONFIG_KPROBES=y" >> $CONFIG_FILE
        echo "CONFIG_HAVE_KPROBES=y" >> $CONFIG_FILE
        echo "CONFIG_OVERLAY_FS=y" >> $CONFIG_FILE

        #不知道
        echo "CONFIG_MT7601U=y" >> $CONFIG_FILE
        echo "CONFIG_WL_MEDIATEK=y" >> $CONFIG_FILE
        echo "WL_MEDIATEK=y" >> $CONFIG_FILE
               
    - name: 设置ccache缓存
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: build-kernel-mido-kernel
        max-size: 4G

    - name: 切换python2.7
      run: |
       sudo rm /bin/python
       sudo ln -s /bin/python2.7 /bin/python
 
    - name: 开始编译内核
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        export TARGET_PRODUCT=full_oppo6771_${{ github.event.inputs.device }}
        export OPPO_TARGET_DEVICE=oppo6771_${{ github.event.inputs.device }}
        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$GITHUB_WORKSPACE/kernel_workspace/gcc64/bin:$GITHUB_WORKSPACE/kernel_workspace/gcc32/bin:$PATH
        export KBUILD_BUILD_HOST=酷安@Xinran_StarBai
        export KBUILD_BUILD_USER=ShirokoNeko-KSU-Xinran_StarBai
        
        # 编译配置
        make -s -j$(nproc --all) O=out ARCH=arm64 oppo6771_${{ github.event.inputs.device }}_defconfig
        
        # 编译内核并记录日志
        make -j$(($(nproc --all)-1)) \
         CC="ccache clang" \
         O=out \
         ARCH=arm64 \
         CLANG_TRIPLE=aarch64-linux-gnu- \
         CROSS_COMPILE=aarch64-linux-android- \
         CROSS_COMPILE_ARM32=arm-linux-androideabi- \
         KCFLAGS="-fno-pie"
         
    - name: 验证内核镜像
      run: |
        FILE_PATH="$GITHUB_WORKSPACE/kernel_workspace/android-kernel/out/arch/arm64/boot/Image.gz-dtb"
        if [ -f "$FILE_PATH" ]; then
        echo "内核镜像存在，大小: $(du -h $FILE_PATH | cut -f1)"
        else
        echo "错误：内核镜像未生成!"
        ls -la "$GITHUB_WORKSPACE/kernel_workspace/android-kernel/out/arch/arm64/boot"
        exit 1
        fi
        
    - name: 克隆 AnyKernel3 并打包
      run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out/arch/arm64/boot
          git clone https://github.com/Winkmoon/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          cd AnyKernel3
          cp $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out/arch/arm64/boot/Image.gz-dtb ./Image.gz-dtb
          if [ ! -f ./Image.gz-dtb ]; then
            exit 1
          fi
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            zip -r ../AnyKernel3_SukiSU_${{ env.KSUVER }}_${{ env.KERNEL_VERSION }}_A11_${{ github.event.inputs.kernel_suffix }}.zip ./*
          else
            zip -r ../AnyKernel3_SukiSU_${{ env.KSUVER }}_${{ env.KERNEL_VERSION }}_A11_${{ env.KERNEL_NAME }}.zip ./*
          fi
      
    - name: 上传 ZIP
      uses: actions/upload-artifact@v4
      with:
          name: AnyKernel3_SukiSU_${{ env.KSUVER }}_${{ env.KERNEL_VERSION }}_A11_${{ env.KERNEL_NAME }}
          path: kernel_workspace/android-kernel/out/arch/arm64/boot/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
      
    steps:
      - name: 下载 ZIP 工件
        uses: actions/download-artifact@v4
        with:
          name: AnyKernel3_SukiSU_${{ env.KSUVER }}_${{ env.KERNEL_VERSION }}_A11_${{ env.KERNEL_NAME }}
          path: ./release_zips
